name: web_socket_cli
description: A cross-platform WebSocket client with support for headers and followRedirects.
version: 0.0.1
homepage: https://github.com/C0DE-IN/web_socket_cli.git

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  universal_io: ^2.2.2
